settings:
  private: false
  has_issues: true
  has_wiki: true
  has_projects: true
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: false
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

branch_protections:
  - name: main
    exists: true
    protection:
      pr_options: null
      required_status_checks: null
      enforce_admins: true
      require_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true
      restrictions: null
