settings:
  private: false
  has_issues: true
  has_wiki: true
  has_projects: true
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: false

branch_protections:
  - name: main
    exists: true
    protection:
      required_status_checks: null
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      require_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      block_creations: true
      required_conversation_resolution: true
      lock_branch: false
  