name: Setting Specification Matrix Global

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  # Get Repositories in Organization
  get-org-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@v3
        id: get-org-repos
        with:
          github-token: ${{ secrets.ORG_ACCESS_TOKEN }}
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}
  
  # Works up to 256 Repositories (Matrix Limit)
  setting-spec:
    runs-on: ubuntu-latest
    needs: get-org-repos
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actuarysailor/gha-repo-manager@v2
        with:
          action: apply
          settings_file: .github/spec/setting.yml
          repo: TSLedger/${{ matrix.repo }}
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          
