name: Setting Specification Matrix Global

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-repositories:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/get-org-repos@v3
        id: get-org-repos
        with:
          github-token: ${{ secrets.TOKEN }}
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}
  setting-spec:
    runs-on: ubuntu-latest
    needs: get-repositories
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-org-repos.outputs.repos) }}
      fast-fail: false
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/spec/setting.yml
      - uses: actuarysailor/gha-repo-manager@v2
        with:
          action: apply
          setting_file: .github/spec/setting.yml
          repo: ${{ matrix.repo }}
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
          
